api_controllers:
    resource:
        path: ../src/Presentation/API/Controller/
        namespace: App\Presentation\API\Controller
    type: attribute

command_controllers:
    resource:
        path: ../src/Command/
        namespace: App\Command
    type: attribute
